// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB3R0rlH3OKFSpObV7HmQBwoxBJe1BxEE',
    appId: '1:78602373009:web:970fa38eac6be1197abc30',
    messagingSenderId: '78602373009',
    projectId: 'restaurant-management-bb01e',
    authDomain: 'restaurant-management-bb01e.firebaseapp.com',
    storageBucket: 'restaurant-management-bb01e.firebasestorage.app',
    measurementId: 'G-M3HV1TR540',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOkSeEf1fNBrAhwyiyW5VrqgRzm233Sqw',
    appId: '1:78602373009:android:507d49fc3adad57e7abc30',
    messagingSenderId: '78602373009',
    projectId: 'restaurant-management-bb01e',
    storageBucket: 'restaurant-management-bb01e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAufXaYTMsGZkBkDZcc45BCxC8_er_gfOk',
    appId: '1:78602373009:ios:c2e7b2d20f0ac6297abc30',
    messagingSenderId: '78602373009',
    projectId: 'restaurant-management-bb01e',
    storageBucket: 'restaurant-management-bb01e.firebasestorage.app',
    iosClientId: '78602373009-ua61qdb92denn4uue50ov7nkrijii286.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAufXaYTMsGZkBkDZcc45BCxC8_er_gfOk',
    appId: '1:78602373009:ios:c2e7b2d20f0ac6297abc30',
    messagingSenderId: '78602373009',
    projectId: 'restaurant-management-bb01e',
    storageBucket: 'restaurant-management-bb01e.firebasestorage.app',
    iosClientId: '78602373009-ua61qdb92denn4uue50ov7nkrijii286.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB3R0rlH3OKFSpObV7HmQBwoxBJe1BxEE',
    appId: '1:78602373009:web:df0ee664e7fe229c7abc30',
    messagingSenderId: '78602373009',
    projectId: 'restaurant-management-bb01e',
    authDomain: 'restaurant-management-bb01e.firebaseapp.com',
    storageBucket: 'restaurant-management-bb01e.firebasestorage.app',
    measurementId: 'G-DVNGKS3SEE',
  );
}
